server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service